- .eslintrc.js
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/technical-specification.md
- .github/dependabot.yml
- .github/pull_request_template.md
- .gitignore
- README.md
- commitlint.config.js
- package-lock.json
- package.json
- renovate.json
- src/server/index.ts
- tsconfig.json
In order to demonstrate software design patterns, we must first decide on a production language and have a basic server running. Additionally, we should take advantage of Github features and add templates for PRs, issues etc.
Javascript is a loosely-typed language. While this can be convenient, building a major project on top of a loosely-typed language can lead to hours of lost time debugging or production rollbacks due to server crashes. Using a statically-typed language such as Typescript will help developers catch mistakes early in the development process, and provide an enhanced IDE experience when inspecting types.
This PR sets up the necessary tooling so that developers can get straight into the code without hassle.
**Features**:
- Hot reloading during development
- Pre-configured …
> Introduce Typescript as the default language for the server

- Dockerfile.development
- Dockerfile.production
- docker-compose.yml
- package.json
- src/server/index.ts
We would like to have reproducible builds so that we can (1) avoid the problems that come with developer's coding in their own custom laptop environment, and (2) have a reproducible build in production.
_"But it works on my machine!"_
Introduce Dockerfiles for development and production environments.
The aim here is simplicity - the host machine's files are simply mounted into the docker container via docker-compose before executing an install and starting nodemon.
This Docker build aims to achieve improved security and size optimisations by
1. Going with a minimal Alpine OS and reduce the final image size/attack surface
2. Using a two-stage build so that installation dependencies are not required in the final image
3. Only copying transpiled files from _build_, instead of source files …
> Docker for development and production

- package-lock.json
- package.json
`ts-node-dev` shares the Typescript compilation process between restarts, which significantly
increases the speed of restarting.
**New dev dependencies**:
- `ts-node-dev` 
**Deprecated**:
- `nodemon`
- `ts-node`
> Replace nodemon and ts-node with ts-node-dev

- .github/workflows/ci.yml
The step to push an image to ECR never runs
Line 96 is never consistently true since the jobs run in parallel. 
```
- name: Push to ECR
if: needs.gatekeep.outputs.proceed == 'true'
```
This solution ensures that the gatekeep job is run before the build job.
> build(ci): add dependency

- guides/DEPLOYING.md
Summary of proposed changes:
1) Reorder network config to be at the top. Security groups are managed per VPC, and without first selecting the correct VPC you will not be able to select the instance security group. 
2) Add reminder that S3 bucket permissions need to be setup separately.
> feat: add details to elastic beanstalk setup

- guides/BASTION_SERVER.md
Based on the current deployment guide, a bastion server is necessary for direct access to the production database.  However, there are currently no instructions written in the guide at the moment.
This PR includes a guide to creating a bastion server and connecting it to the production database
> docs(guide): adding guide for creation of bastion server

- backend/src/bootstrap/index.ts
_What problem are you trying to solve? What issue does this close?_
bodyparser has been deprecated.
Replace with `express.json()` 
_How did you solve the problem?_
Use built in bodyparser in express 4+
**Features**:
- Details ...
**Improvements**:
- Details ...
**Bug Fixes**:
- Details ...
**BEFORE**:
[insert screenshot here]
**AFTER**:
[insert screenshot here]
_What tests should be run to confirm functionality?_
_Notes regarding deployment of the contained body of work. These should note any
new dependencies, new scripts, etc._
**New environment variables**:
- `env var` : env var details
**New scripts**:
- `script` : script details
**New dependencies**:
- `dependency` : dependency details
**New dev dependencies**:
- `dependency` : dependency details
> fix: replace deprecated bodyparser

- guides/deploying/AWS.md
VPC creation section could do with more details.
I asked Pallani for a second opinion and he said it was okay to use the AWS defaults. Think we can go with that for ease of learning/consistency (when in doubt, just use AWS defaults).
But if you think we should use `172.31.0.0/16` instead, I'll make the change. Thanks!
> More specific configuration for creating VPCs

- .github/CODEOWNERS
All repositories should have a primary owner (typically a team). This should be documented in the file `.github/CODEOWNER` (see doc [here](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-code-owners#example-of-a-codeowners-file))
Add basic CODEOWNER file to repo
cc @LoneRifle @liangyuanruo
> feat(codeowner): Add file .github/CODEOWNER

- .husky/_/husky.sh
- backend/package-lock.json
- backend/package.json
- backend/src/app.module.ts
- backend/src/config/config.schema.ts
- backend/src/health/health.controller.spec.ts
- backend/src/health/health.controller.ts
- backend/src/health/health.module.ts
This pull request implemented the healthcheck endpoint as part of the standard flows on ts-template. The health check endpoint checks that the memory usage does not cross a configurable threshold and the connectivity to any external services (db). 
The healthcheck endpoint makes use of the `@nestjs/terminus` module. It uses built in memory checks and sequelize db ping checks.
**Features**:
- Endpoint `/api/health` that returns the status of services. The expected response when services are up is as follows: 
```
{
"status": "ok",
"info": {
"database": {
"status": "up"
},
"memory_heap": {
"status": "up"
},
"memory_rss": {
"status": "up"
}
},
"error": {},
"details": {
"database": {
"status": "up"
},
"memory_heap": {
"status": "up"
},
"memory_rss": {
"status": "up"
}
}
}
```
**New …
> feat: implements healthcheck endpoint

- backend/package-lock.json
- backend/package.json
- frontend/package-lock.json
- frontend/package.json
Use a wildcard for `@types/node`, since that is often tied to node runtime anyway.
> build(deps-dev): use wildcard for @types/node

- .github/workflows/ci.yml
- docs/deploying/For-Engineers.md
"To harden the security for [the] CI/CD pipeline, [we] can make use of OpenID connect to assume an IAM role in your AWS account rather than creating a IAM user and passing long-lived sensitive secrets in GitHub as secrets." ~ @lamkeewei 
**New environment variables for GITHUB ACTIONS**:
- `AWS_ROLE_ARN` : AWS role GitHub Action will assume
- `AWS_REGION`: AWS region
> chore: use github oidc for ci

- .github/workflows/ci.yml
- Ensure that AWS_ROLE_ARN and AWS_REGION are obtained via Secrets,
the simplest way of introducing the values into env vars
- Gate proceeding with Configuring AWS Credentials
by ensuring that those values are present
> fix(ci): gatekeep Configure AWS Credentials

- .github/workflows/aws-deploy.yml
- .github/workflows/ci.yml
- docs/deploying/For-Engineers.md
- ecs-task-definition.json
Given Elastic Beanstalk has fallen out of favour, rework CI to deploy to ECS, assuming separate accounts for staging and prod
- Port aws-deploy GitHub Action from Health Appointment System
- Polish ci steps for names, punctuation
- Remove references to AWS in build and deploy steps, relying on the new aws-deploy action
- Crucially, handle both push to ECR repo and actual deploy in a single step
> build(ci): drop Elastic Beanstalk, use ECS

- backend/src/config/config.schema.ts
- backend/src/mailer/mailer.service.ts
- docs/deploying/for-everyone.md
- docs/deploying/for-hustlers.md
Allow mailer to be configurable using environment variables, so that we can deploy ts-template to environments other than AWS and use mail services that use SMTPS. AWS deployments will still require the use of SES over REST API.
- Move hard-coded nodemailer config for dev environments to dev-level defaults in `config.schema`
- Allow these to be changed through the env vars `MAILER_HOST` and `MAILER_PORT`
- Introduce `MAILER_USER` and `MAILER_PASSWORD` to allow users to supply credentials to SMTP services in production
- Update the guides to reflect the changes
- `MAILER_*` : for users to configure SMTP credentials in production
> feat(mailer): allow config via env vars

- package.json
- wait-for-it.sh
To adhere to the Principle of Least Surprise, wait for postgres to 
initialise in `npm run dev` before starting the app
> chore(docker): wait for postgres before app init

- .github/workflows/ci.yml
We want to minimise set-up overhead when building and prototyping their product. Requiring them to set up both staging and production environments just to deploy to one of them seems a bit unfair.
Allow secrets for deployments to be set just for staging or for production, so that teams can set up just one environment to deploy to while still prototyping their application
> build(ci): split proceed step to per-env

- ecs-task-definition.json
- Declare `NODE_ENV` as `production` for all deployed environments
- Pass new `DD_TAGS_AGENT` param to dd-agent as `DD_TAGS`
> build(ci): hardcode `NODE_ENV`, have discrete `DD_TAGS_AGENT`

- .github/workflows/aws-deploy.yml
- .github/workflows/ci.yml
- .github/workflows/deploy.yml
- Drop generate-docker-tag step, supply tag directly
- Create deploy workflow call, wrapping around ECS/Fly/Proceed steps
- Replace deploy-related steps in ci.yml with new workflow calls
> build(ci): reorg deploy actions for readability

- ecs-task-definition.json
Don't think `DD_SOURCE` is needed inside the container as it can't be found on https://docs.datadoghq.com/containers/docker/?tab=standard#environment-variables. Removing to save the trouble of having to set it in SSM.
> chore: hardcode DD_SOURCE env var

- backend/src/auth/__tests__/auth.controller.spec.ts
- backend/src/auth/__tests__/auth.service.spec.ts
- backend/src/mailer/mailer.service.ts
When deploying ts-template for the first time to production, mail services may not have been set up, due to the slow and arduous process of requesting for mail services like AWS' SES, which requires manual support tickets to fully enable.
Closes #2226
As a (somewhat questionable) workaround, simply log mails instead of sending them to any mail service.
This has the nice side-effect of forcing new products to go through the process of making a code change and making environment changes, thereby familiarising them with the set-up.
TODO: Write a guide that explicitly walks them through said process.
> chore(mailer): log mail instead of sending in prod

- backend/src/app.module.ts
- backend/src/core/providers/logged-validation.pipe.ts
- backend/src/database/entities/user.entity.ts
- frontend/src/features/auth/components/LoginForm.tsx
- package-lock.json
- package.json
- shared/package.json
- shared/src/decorators/__tests__/is-gov-sg-email.spec.ts
- shared/src/decorators/is-gov-sg-email.ts
- shared/src/types/auth.dto.ts
Use class-validator and class-transformer to validate VerifyOtpRequest and form validation to ensure that the login is a valid gov.sg email. This guards against a bad actor providing input that is not an email address (eg, two email addresses separated by ,), but can still be used by nodemailer
- install class-validator and class-transformer to root directory to allow backend and shared to use the same instances for validation
- create a new `IsGovSgEmail()` decorator that builds on top of `IsEmail()` to ensure that an address is a valid gov.sg email
- add a validation pipe to the app to enable request validation
- ensure that the emails in GenerateOtpDto and User are annotated with `IsGovSgEmail()` and hence validated, along with mail input
- `class-validator` and `class-transformer` : …
> fix(auth): validate login emails

- backend/package-lock.json
- backend/package.json
- backend/src/config/config.schema.ts
- backend/src/mailer/mailer.service.ts
- frontend/package-lock.json
Setting up ts-template applications to send OTP emails can be cumbersome. Postman is the most
convenient way to do so, but ts-template currently lacks the plumbing to facilitate this
Take advantage of Postman's transactional API, which is much easier to set up than AWS SES
- Introduce a new env var - `POSTMANGOVSG_API_KEY`
- Use new env var to configure a nodemailer transport for Postman, falling back on logging the OTP
- Remove aws-sdk, no longer used
- Take the chance to refresh `frontend/package-lock.json`
> feat(mailer): replace SES with Postman

- backend/package-lock.json
- backend/package.json
- backend/src/config/config.schema.ts
- Set `OTP_EMAIL` to a sensible default to allow Postman to smoothly send emails
- Update @opengovsg/postmangovsg-client so that sender name can be rendered into emails
> fix(config): set OTP_EMAIL default, update npm to facilitate Postman

- backend/src/database/migrations/1659538032978-initial.ts
The initial migration for TypeORM was missing the destroyedAt column, so add this
> fix(migrations): add `destroyedAt` column

- backend/src/database/ormconfig.ts
TypeORM treats `synchronize` and migrations as separate processes; using one will break the other. Stick to using migrations as this is the accepted practice of rolling out database schema changes, and lean on TypeORM's first class support for migrations.
Replace `synchronize` with config for migrations
> feat(ormconfig): replace `synchronize` with `migrationsRun`

- backend/src/database/ormconfig.ts
The excess `.` causes migrations to fail on app load.
> chore: remove excess `.` in migrations path in `ormconfig.ts`

- backend/.env.development
- backend/.env.test
Default environment variable populated for `OTP_EMAIL` is wrong and will not be accepted by Postman. Currently, when the Postman API key is added, the OTP emails will still fail, with a 400 status error from Postman and a 500 error thrown by the app's backend.
**Bug Fixes**:
- Remove the environment variable `OTP_EMAIL` so that the correct value specified in `config.schema.ts` will be loaded.
> fix: remove OTP_EMAIL to use correct Postman no-reply email

- backend/src/auth/auth.service.ts
- backend/src/otp/otp.service.ts
Users were unable to login if they were to use upper case anywhere in their email when trying to login, and were thrown a "Incorrect OTP given" error.
Convert email to lowercase before using it as part of the secret. 
**Improvements**:
- Since emails should be case-insensitive, the emails which users are based on should be case-insensitive as well
Login with using emails which have upper case characters. User should be able to:
1. Key in the received OTP and login successfully
2. User should be able to access the same data regardless of what casing they typed their emails in when they logged in
> fix/otp: treat email login inputs as case-insensitive

- backend/src/auth/auth.service.ts
Apply DRY and use `otp.sender_name` from convict to specify both the sender and the application name in the subject
> refactor(auth): use `otp.sender_name` in subject

- .eslintignore
- .eslintrc.js
- .prettierrc.js
- backend/.eslintrc.js
- backend/package-lock.json
- backend/package.json
- frontend/.eslintrc.js
- frontend/package-lock.json
- frontend/package.json
- package-lock.json
- package.json
- shared/.eslintrc.js
- shared/package-lock.json
- shared/package.json
To simplify our codebase, we want to trim (or at least spin out) as much of our linting config as possible
Rework our linter to use a consolidated ruleset, trimming out as many rules and config as we can without affecting our codebase
- Use eslint-config-opengovsg, replacing all our other eslint-config
- Trim as much as we can from eslintrc files and supporting cast
- Drop prettier and supporting cast, since those are now implemented as a linting/formatting rule in eslint-config-opengovsg, which uses its own .prettierrc
> build: use eslint-config-opengovsg, trim rules

- .eslintrc.js
- backend/src/auth/auth.controller.ts
- backend/src/auth/auth.module.ts
- backend/src/database/database-config.service.ts
- backend/src/mailer/mailer.module.ts
- backend/src/otp/otp.module.ts
- frontend/.eslintrc.js
- frontend/config-overrides.js
To simplify our linting infrastructure, drop our custom import rules and enforce the default ones.
Take the chance to remove spurious ignore patterns while we are here
> build(lint): drop custom import grouping rules

- .eslintrc.js
- backend/src/core/providers/logged-validation.pipe.ts
We want to enforce the no-unused-args with its defaults, but we have to rewrite the one block of code that triggers
a warning as a result
Rewrite flatten errors to avoid non-null assertion and unused arg, with the nice side-effect of doing so in a single pass
- Rework `flattenErrors()` such that in a single pass, split each ValidationError into the error itself and its children.
- Flat-map the two into an array containing the error, and the result from `flattenErrors(children)`
- Drop the custom options for no-unused-args, and enforce rule defaults
> refactor(validation): flatten errors in single pass

- frontend/.eslintrc.js
- frontend/src/app/App.tsx
- frontend/src/app/AppRouter.tsx
- frontend/src/app/PrivateElement.tsx
- frontend/src/app/PublicElement.tsx
- frontend/src/features/auth/api/fetchUser.ts
- frontend/src/features/auth/api/sendLoginOtp.ts
- frontend/src/features/auth/api/verifyLoginOtp.ts
- frontend/src/features/auth/components/LoginForm.tsx
- frontend/src/features/auth/components/LoginImageSvgr.tsx
- frontend/src/features/auth/components/OtpForm.tsx
- frontend/src/features/auth/components/ResendOtpButton.tsx
- frontend/src/features/auth/routes/LoginPage.tsx
- frontend/src/features/dashboard/routes/DashboardPage.tsx
- frontend/src/features/health/api/queries.ts
- frontend/src/lib/auth.tsx
In a bid to simplify our linting config, we need to remove as many of our own custom rules as we can
As discussed with @karrui, remove custom import groups for frontend, and relint codebase
> build(lint): remove custom import groups

- .eslintrc.js
- backend/.eslintrc.js
- backend/package.json
- frontend/.eslintrc.js
- frontend/package-lock.json
- frontend/package.json
- shared/.eslintrc.js
- shared/package.json
Reduce linting config to a bare minimum, in the name of simplification
- Harmonise lint command across all workspaces
- Configure root `.eslintrc.js` to lint frontend files, even `.ts`
- Remove workspace-specific linting config
> build(lint): reduce eslint config to single file

- backend/src/app.module.ts
Assume we have an API endpoint: `/items/*`.
Currently, an invalid path like:
`/item/nonsense` (note that it's `item` without `s`)
will give HTTP 200 and default HTML content instead of non HTTP 2xx.
This is wrong.
We should disable `fallthrough` in `serveStaticOptions`. We should not let unhandled paths be "handled" by this module.
Please refer to [serveStaticOptions docs](https://github.com/nestjs/serve-static/blob/master/lib/interfaces/serve-static-options.interface.ts#L52) for more information.
> fix: disable fallthrough so that invalid paths do not give HTTP 200

- docs/deploying/for-engineers.md
In reference to this blog post published yesterday:
https://github.blog/changelog/2023-06-27-github-actions-update-on-oidc-integration-with-aws/
It appears that the CloudFormation stack should be updated to prevent possible failures
> docs: update github thumbprint list

- backend/src/app.module.ts
- backend/src/main.ts
Our traces currently don't have accompanied logs due to improper initialisation order as described in https://github.com/DataDog/dd-trace-js/issues/2189#issuecomment-1188455882. This PR moves importing of tracer at the start (before pino is instantiated/imported)
> chore(backend): update dd-trace import location
